## Begin registration

### Successful
POST http://localhost:3000/registration/begin HTTP/1.1
content-type: application/json

{
    "name" : "john",
    "displayName" : "John Doe"
}

### Invalid 
POST http://localhost:3000/registration/begin HTTP/1.1
content-type: application/json

{
    "name": " ",
    "displayName": " "
}

### Invalid 
POST http://localhost:3000/registration/begin HTTP/1.1
content-type: application/json

{}

### Invalid 
POST http://localhost:3000/registration/begin HTTP/1.1
