cabal-version: 3.8
name: reacthome-core
version: 0.1.0.0
synopsis: Core Domain
description: A core domain of Reacthome applications galaxy
license: BSD-3-Clause
author: ReactHome Team
maintainer: gazdovsky@gmail.com
category: Web
build-type: Simple

library
  hs-source-dirs: src
  -- cabal-gild: discover src
  exposed-modules:
    Reacthome.Core.Capabilities
    Reacthome.Core.Capabilities.Adjustable
    Reacthome.Core.Capabilities.Switchable
    Reacthome.Core.Connector
    Reacthome.Core.Device
    Reacthome.Core.Net
    Reacthome.Core.Site
    Reacthome.Core.Store

  build-depends:
    aeson,
    base,
    containers,
    text,
    uuid,

  default-language: GHC2024
  default-extensions:
    BlockArguments
    DuplicateRecordFields
    OverloadedRecordDot
    OverloadedStrings
    RecordWildCards
