cabal-version: 3.8
name: reacthome-domain
version: 0.1.0.0
synopsis: Reacthome Domain
description: Reacthome Domain Server
license: BSD-3-Clause
author: ReactHome Team
maintainer: gazdovsky@gmail.com
category: Web
build-type: Simple

common common-options
  build-depends:
    base,
    ws,

  default-language: GHC2024
  default-extensions:
    BlockArguments
    DeriveAnyClass
    DerivingStrategies
    DuplicateRecordFields
    ImplicitParams
    OverloadedRecordDot
    OverloadedStrings
    RecordWildCards

library
  import:
    common-options

  -- cabal-gild: discover src
  exposed-modules:
    Reacthome.Domain.App
    Reacthome.RBUS.Serial
    Reacthome.RBUS.UDP

  build-depends:
    text,
    uuid,

  hs-source-dirs: src

executable reacthome-domain
  import:
    common-options

  build-depends:
    reacthome-domain

  hs-source-dirs: app
  main-is: Main.hs
