## OAuth2

### Redirect
GET http://localhost:3000/?response_type=code&state=1&redirect_uri=1&client_id=11 HTTP/1.1

### Missing parameter `client_id` of the `AuthorizationCodeGrant` flow
GET http://localhost:3000/?response_type=code&state=123&redirect_uri=test HTTP/1.1

### Missing parameter `redirect_uri` of the `AuthorizationCodeGrant` flow
GET http://localhost:3000/?response_type=code&state=123 HTTP/1.1

### Missing parameter `state` of the `AuthorizationCodeGrant` flow
GET http://localhost:3000/?response_type=code HTTP/1.1

### Unknown type of the OAuth2 authorization flow
GET http://localhost:3000/?response_type=unknown HTTP/1.1

### Not a valid `OAuth2` flow
GET http://localhost:3000/ HTTP/1.1

### Method Not Allowed
POST http://localhost:3000/ HTTP/1.1
