cabal-version: 3.8
name: util
version: 0.1.0.0
synopsis: Common Utilities
description: A collection of common utilities for Reacthome daemons galaxy
license: BSD-3-Clause
author: ReactHome Team
maintainer: gazdovsky@gmail.com
category: Web
build-type: Simple

library
  hs-source-dirs: src
  -- cabal-gild: discover src
  exposed-modules:
    Util.ASN1
    Util.Aeson
    Util.Channel
    Util.Encoding.Base64
    Util.Encoding.Base64.Lazy
    Util.Encoding.Base64.URL
    Util.Encoding.Base64.URL.Lazy
    Util.Encoding.Error
    Util.Encoding.UUID
    Util.Encoding.Utf8
    Util.Encoding.Utf8.Lazy
    Util.MVar
    Util.SQLite
    Util.Timer

  build-depends:
    aeson,
    asn1-encoding,
    base,
    base64-bytestring,
    bytestring,
    errors,
    resource-pool,
    sqlite-simple,
    stm,
    text,
    uuid,

  default-language: GHC2024
  default-extensions:
    BlockArguments
    DeriveAnyClass
    OverloadedStrings
    RecordWildCards
