cabal-version: 3.8
name: reacthome-logic
version: 0.1.0.0
synopsis: Reacthome Logic
description: Reacthome Logic Server
license: BSD-3-Clause
author: ReactHome Team
maintainer: gazdovsky@gmail.com
category: Web
build-type: Simple

common common-options
  build-depends:
    base,
    ws,

  default-language: GHC2024
  default-extensions:
    BlockArguments
    DeriveAnyClass
    DerivingStrategies
    DuplicateRecordFields
    ImplicitParams
    OverloadedRecordDot
    OverloadedStrings
    PatternSynonyms
    RecordWildCards

library
  import:
    common-options

  -- cabal-gild: discover src
  exposed-modules:
    Reacthome.Logic.App
    Reacthome.Logic.Data.Capabilities.Adjustable
    Reacthome.Logic.Data.Capabilities.Switchable
    Reacthome.Logic.Data.Core.Capabilities
    Reacthome.Logic.Data.Core.Connector
    Reacthome.Logic.Data.Core.Device
    Reacthome.Logic.Data.Core.Net
    Reacthome.Logic.Data.Core.Site
    Reacthome.Logic.Data.Core.Store
    Reacthome.Logic.Error
    Reacthome.Logic.Glue.Controller
    Reacthome.Logic.Glue.Env
    Reacthome.Logic.Glue.Evaluator
    Reacthome.Logic.Glue.Lib.Vision
    Reacthome.Logic.Glue.Lib.Vision.Get
    Reacthome.Logic.Glue.Sink
    Reacthome.Logic.Server

  build-depends:
    async,
    bytestring,
    containers,
    glue,
    text,
    unagi-chan,
    uuid,

  hs-source-dirs: src

executable reacthome-logic
  import:
    common-options

  build-depends:
    reacthome-logic

  hs-source-dirs: app
  main-is: Main.hs
